version: '3'
services:
  web:
    image: nginx
    ports: 
      - 8000:80
    volumes:
      - "./web:/var/www/html"
      - "./etc/nginx:/etc/nginx/conf.d"
    restart: always
    container_name: nginx_server
    depends_on:
      - php
      - db
  php:
    image: nanoninja/php-fpm
    restart: always
    container_name: php_server
    volumes:
      - "./web:/var/www/html"
  db:
    image: mysql
    container_name: mysql_server
    restart: always
    environment:
      - MYSQL_DATABASE=test 
      - MYSQL_ROOT_PASSWORD=root mysql
    command: "--default-authentication-plugin=mysql_native_password"
  admin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql_server
    restart: always
    depends_on:
      - db



  
